nfq_library_root:
    path:     /
    defaults: { _controller: NfqLibraryBundle:Homepage:index }

nfq_library_homepage:
    path:     /home
    defaults: { _controller: NfqLibraryBundle:Homepage:index }

newBooks:
    path:     /list/{type}
    defaults: { _controller: NfqLibraryBundle:BookList:list }

bookinfo:
    path:     /book/{id}
    defaults: { _controller: NfqLibraryBundle:BookInfo:index }

booklist_search:
    path:     /search
    defaults: { _controller: NfqLibraryBundle:BookList:search }

booklist_search_keyword:
    path:     /search/{keyword}
    defaults: { _controller: NfqLibraryBundle:BookList:search }

add_order:
    path:     /order/{descriptionId}
    defaults: { _controller: NfqLibraryBundle:Order:AddOrder }

admin_panel:
    path:     /admin
    defaults: { _controller: NfqLibraryBundle:Admin:Index }

return_order:
    path:     /admin/return/{orderId}
    defaults: { _controller: NfqLibraryBundle:Admin:return }

add_book_get:
    path:     /add
    defaults: { _controller: NfqLibraryBundle:Admin:addBook }
    
add_book:
    path:     /add/{isbn}
    defaults: { _controller: NfqLibraryBundle:Admin:addBook }
    
show_orders:
    path:     /showOrders
    defaults: { _controller: NfqLibraryBundle:Order:showOrders }