nfq_library_root:
    path:     /
    defaults: { _controller: NfqLibraryBundle:Homepage:index }

nfq_library_homepage:
    path:     /home
    defaults: { _controller: NfqLibraryBundle:Homepage:index }

newBooks:
    path:     /new
    defaults: { _controller: NfqLibraryBundle:Homepage:newBooks }

popularBooks:
    path:     /popular
    defaults: { _controller: NfqLibraryBundle:Homepage:popularBooks }

bookinfo:
    path:     /book/{id}
    defaults: { _controller: NfqLibraryBundle:BookInfo:index }
    
booklist_books:
    path:     /books
    defaults: { _controller: NfqLibraryBundle:BookList:books }
    
booklist_books_type:
    path:     /books/{type_of_list}
    defaults: { _controller: NfqLibraryBundle:BookList:books }

booklist_search:
    path:     /search
    defaults: { _controller: NfqLibraryBundle:BookList:search }

booklist_search_keyword:
    path:     /search/{keyword}
    defaults: { _controller: NfqLibraryBundle:BookList:search }

add_order:
    path:     /order/{descriptionId}
    defaults: { _controller: NfqLibraryBundle:BookInfo:AddOrder }

show_orders:
    path:     /orders/{userId}
    defaults: { _controller: NfqLibraryBundle:BookInfo:getOrders }