nfq_library_root:
    path:     /
    defaults: { _controller: NfqLibraryBundle:Homepage:index }

nfq_library_homepage:
    path:     /home
    defaults: { _controller: NfqLibraryBundle:Homepage:index }

email:
    path:     /mail
    defaults: { _controller: NfqLibraryBundle:Admin:Email }

newBooks:
    path:     /list/{type}
    defaults: { _controller: NfqLibraryBundle:BookList:list }

bookinfo:
    path:     /book/{id}
    defaults: { _controller: NfqLibraryBundle:BookInfo:index }

booklist_search:
    path:     /search
    defaults: { _controller: NfqLibraryBundle:BookList:search }

booklist_search_keyword:
    path:     /search/{keyword}
    defaults: { _controller: NfqLibraryBundle:BookList:search }

add_order:
    path:     /order/{descriptionId}
    defaults: { _controller: NfqLibraryBundle:Order:AddOrder }

admin_panel:
    path:     /admin
    defaults: { _controller: NfqLibraryBundle:Admin:Index }
