Nfq\LibraryBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        lastname:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''